// 이곳은 던파소스에 없는 순수 스크립트로만 개발하면서 필요한 스킬개발에 필요한 상수,enum 추가값을 선언하는 부분입니다. 
// 던파소스에 있는 값을 이곳에 넣으시면 안됩니다.

STATE_BURSTER				<- 100	// 공통스킬 state 버스터

// 공통 skill관련 부분입니다.
// 198	`ATMage/Buster.skl`				// 버스터
SKILL_BURSTER				<- 198	// 공통스킬 버스터


VECTOR_FLAG_0	<- 0
VECTOR_FLAG_1	<- 1
VECTOR_FLAG_2	<- 2
VECTOR_FLAG_3	<- 3
VECTOR_FLAG_4	<- 4
VECTOR_FLAG_5	<- 5

SKL_STATIC_INT_IDX_0	<- 0
SKL_STATIC_INT_IDX_1	<- 1
SKL_STATIC_INT_IDX_2	<- 2
SKL_STATIC_INT_IDX_3	<- 3
SKL_STATIC_INT_IDX_4	<- 4
SKL_STATIC_INT_IDX_5	<- 5
SKL_STATIC_INT_IDX_6	<- 6
SKL_STATIC_INT_IDX_7	<- 7
SKL_STATIC_INT_IDX_8	<- 8

SKL_LVL_COLUMN_IDX_0	<- 0
SKL_LVL_COLUMN_IDX_1	<- 1
SKL_LVL_COLUMN_IDX_2	<- 2
SKL_LVL_COLUMN_IDX_3	<- 3
SKL_LVL_COLUMN_IDX_4	<- 4
SKL_LVL_COLUMN_IDX_5	<- 5
SKL_LVL_COLUMN_IDX_6	<- 6

PASSIVEOBJ_SUB_STATE_0	<- 10
PASSIVEOBJ_SUB_STATE_1	<- 11
PASSIVEOBJ_SUB_STATE_2	<- 12
PASSIVEOBJ_SUB_STATE_3	<- 13
PASSIVEOBJ_SUB_STATE_4	<- 14
PASSIVEOBJ_SUB_STATE_5	<- 15
PASSIVEOBJ_SUB_STATE_6	<- 16
PASSIVEOBJ_SUB_STATE_7	<- 17

BROKENARROW_UNIQUE_ID <- 9001



VECTOR_I_STATE					<- 0
VECTOR_I_FLAG					<- 1
VECTOR_I_REBIRTH_STATE			<- 2
VECTOR_I_REBIRTH_TIME			<- 3


GHOST_TIME <- 2000
ANGEL_DOWN_TIME <- 1000
DOWN_PAUSE_TIME <- 100






