//技能状态
STATE_RISINGCUTKAI					<- 95

//技能编号
//對應技能表的技能編號
SKILL_RISINGCUTKAI					<- 220

//动画编号
//對應“character/thief/thief.chr”中的[etc motion]
CUSTOM_ANI_RISINGCUTKAI				<- 0
CUSTOM_ANI_RISINGCUTKAI_1           <- 105
CUSTOM_ANI_RISINGCUTKAI_2           <- 106
CUSTOM_ANI_RISINGCUTKAI_3           <- 107
CUSTOM_ANI_RISINGCUTKAI_4           <- 108

//攻击编号
//對應“character/thief/thief.chr”中的[etc attack info]
CUSTOM_ATK_RISINGCUTKAI				<- 0
CUSTOM_ATK_RISINGCUTKAI_1           <- 43



//----默認數值指向---
VECTOR_FLAG_0	<- 0
VECTOR_FLAG_1	<- 1
VECTOR_FLAG_2	<- 2
VECTOR_FLAG_3	<- 3
VECTOR_FLAG_4	<- 4
VECTOR_FLAG_5	<- 5

SKL_STATIC_INT_IDX_0	<- 0
SKL_STATIC_INT_IDX_1	<- 1
SKL_STATIC_INT_IDX_2	<- 2
SKL_STATIC_INT_IDX_3	<- 3
SKL_STATIC_INT_IDX_4	<- 4
SKL_STATIC_INT_IDX_5	<- 5
SKL_STATIC_INT_IDX_6	<- 6
SKL_STATIC_INT_IDX_7	<- 7
SKL_STATIC_INT_IDX_8	<- 8

SKL_LVL_COLUMN_IDX_0	<- 0
SKL_LVL_COLUMN_IDX_1	<- 1
SKL_LVL_COLUMN_IDX_2	<- 2
SKL_LVL_COLUMN_IDX_3	<- 3
SKL_LVL_COLUMN_IDX_4	<- 4
SKL_LVL_COLUMN_IDX_5	<- 5
SKL_LVL_COLUMN_IDX_6	<- 6

SKL_LV_0 <- 0 
SKL_LV_1 <- 1 
SKL_LV_2 <- 2 
SKL_LV_3 <- 3 
SKL_LV_4 <- 4 